### ISSUE TITLE
not compilling on mac

### ISSUE THREAD

**Issue by baralgin1003** [xiaogegexiao/ffmpeg_android_build#1]
I use ndk r13

HEAD is now at 148c4fb8d2... Update for 3.2.2
~/ff
~/ff/ffmpeg ~/ff
ls /Users/admin/ff/openssl-1.0.2k/armeabi-v7a/lib
Makefile:2: config.mak: No such file or directory
Makefile:67: /common.mak: No such file or directory
Makefile:109: /libavutil/Makefile: No such file or directory
Makefile:109: /library.mak: No such file or directory
Makefile:111: /doc/Makefile: No such file or directory
Makefile:198: /tests/Makefile: No such file or directory
make: *** No rule to make target `/tests/Makefile'.  Stop.
/Users/admin/ff/openssl-1.0.2k
/Users/admin/ff/toolchain-android
/Users/admin/ff/toolchain-android/bin/arm-linux-androideabi-gcc is unable to create an executable file.
C compiler test failed.

If you think configure made a mistake, make sure you are using the latest
version from Git.  If the latest version fails, report the problem to the
ffmpeg-user@ffmpeg.org mailing list or IRC #ffmpeg on irc.freenode.net.
Include the log file "config.log" produced by configure as this will help
solve the problem.
Mac-Admin:ff admin$

**Comment by xiaogegexiao** [comment]
@baralgin1003 
Hey baralgin, thanks for reporting. But it seems working on my new macbook pro. Could you make sure that your ffmpeg build is on version n3.2.2?

Since I haven't tried with other ffmpeg versions that I'm not sure if it will work with them.
And plz make sure that your ANDROID_NDK is set in you ~/.bash_profile like this 
`export ANDROID_NDK=/users/path/android-ndk-r13b`. 

Probably worth deleting _toolchain-android_ and _ffmpeg_ and try again.

**Comment by xiaogegexiao** [comment]
@baralgin1003 

Let me know if you still have issue with it. I will close it. If you still have issue, I will reopen it
